local BASH = BASH;
local QUIRK = {};
QUIRK.ID = "morethirst";
QUIRK.Name = "Cotton-mouthed";
QUIRK.Description = "[Thirst] +THIRST | +STAMINA REGEN";
QUIRK.QuirkType = "thirst";
QUIRK.NormalStaminaRegen = 1.66;
QUIRK.ThirstyStaminaRegen = 0.5;
QUIRK.ThirstLength = -1800;
BASH:ProcessQuirk(QUIRK);
