local BASH = BASH;
local ITEM = {};
ITEM.ID =				"satchel_medic";
ITEM.Name =				"Medic Satchel";
ITEM.Description =		"A medium-sized red satchel with a cross insignia that can hold a few belongings.";
ITEM.FlavorText =		"Before God, before their mother, they call on him.";
ITEM.WorldModel =		Model("models/fallout 3/backpack_2.mdl");
ITEM.ModelColor =       Color(200, 0, 0);
ITEM.Weight =			3;
ITEM.Tier =             1;
ITEM.LootHidden =       true;
ITEM.DefaultStock = 	2;
ITEM.DefaultPrice = 	1000;
ITEM.FabricYield =		3;
ITEM.ItemSize =         SIZE_MED;

ITEM.IsAccessory =		true;
ITEM.Inventory =		"inv_satchel";
ITEM.StorageSize =      STORAGE_MED;
BASH:ProcessItem(ITEM);
