local BASH = BASH;
local ITEM = {};
ITEM.ID =				"sunrise_ecologist";
ITEM.Name =				"Ecologist Sunrise";
ITEM.Description =		"Truly the flagship suit of STALKERs Zone-wide. The perfect balance of practicality and protection. Features a simple, first-generation ballistic vest, a standard gasmask, and room for storage. Outfitted with the color scheme of the ecologists.";
ITEM.FlavorText =		"Get out of here, STALKER!";
ITEM.WorldModel =		Model("models/stalkertnb/outfits/sunrise_loner.mdl");
ITEM.Tier =             2;
ITEM.Weight =			8;
ITEM.DefaultStock = 	0;
ITEM.DefaultPrice = 	16000;
ITEM.Durability =		20;
ITEM.FabricYield =		8;
ITEM.ItemSize =         SIZE_MED;

ITEM.IsSuit =			true;
ITEM.PlayerModel =		Model("models/cakez/rxstalker/stalker_merc/stalker_neutral_ecolog_1.mdl");
ITEM.Respiration =      true;
ITEM.BodyArmor = 		25;
ITEM.BurnResist = 		15;
ITEM.AcidResist = 		15;
ITEM.ElectroResist = 	15;
ITEM.ColdResist = 		15;
ITEM.Inventory =		"inv_sunrise";
ITEM.StorageSize =      STORAGE_MED;
BASH:ProcessItem(ITEM);
