local BASH = BASH;
local ITEM = {};
ITEM.ID =				"tundra_male";
ITEM.Name =				"Tundra Jacket (Male)";
ITEM.Description =		"A heavy winter jacket complete with a retro gasmask. Offers a bit more protection than your standard anorak.";
ITEM.FlavorText =		"";
ITEM.WorldModel =		Model("models/stalkertnb/outfits/bandit1.mdl");
ITEM.Tier =             2;
ITEM.Weight =			6;
ITEM.DefaultStock = 	20;
ITEM.DefaultPrice = 	3000;
ITEM.Durability =		10;
ITEM.FabricYield =		5;
ITEM.ItemSize =         SIZE_MED;

ITEM.IsSuit =			true;
ITEM.PlayerModel =		Model("models/stalkertnb/bandit_gasmask.mdl");
ITEM.Respiration =      true;
ITEM.BodyArmor = 		10;
ITEM.BurnResist = 		10;
ITEM.AcidResist = 		10;
ITEM.ElectroResist = 	10;
ITEM.ColdResist = 		15;
ITEM.Inventory =		"inv_anorak";
ITEM.StorageSize =      STORAGE_MED;
BASH:ProcessItem(ITEM);
